- name: Experimenting with fail module
  hosts: "{{ host_group }}"
  become: yes
  
  vars_files:
    - ../vars/local_directories_vars.yml

  remote_user: '{{ remote_host_user }}'
  become_user: '{{ remote_host_user }}'
  
  tasks:
    - name: Running Script
      script: '../playbook-scripts/fail-mod-test.py'
      args:
        executable: python3
      register: test_output
      failed_when: "'Hllo' in test_output.stdout"

