---
- name: Retrieve Flexible I/O Storage Benchmark Results
  hosts: ans-remote2
  become: false

  vars_files:
    - ../vars/local_directories_vars.yml
    - ../vars/remote_vars.yml

  tasks:
  
    - name: Locate log files in remote file system and copy to blank log
      command: "find . -path './*/test-4.log' -exec cp {} /home/{{ remote_host_user }}/fio-results/test7.log \\;"
      args:
        chdir: "/var/lib/phoronix-test-suite/test-results"
