- name: Test Fetching Benchmark Logs
  hosts: "{{ host_group }}"
  become: yes

  vars_files:
    - ../vars/local_directories_vars.yml

  remote_user: '{{ remote_host_user }}'
  become_user: '{{ remote_host_user }}'


  vars_prompt:
    - name: log_dir
      prompt: Type a local directory in which to store CoreMark result logs.
      private: no

  tasks:
    - name: Fetch Benchmark Result Logs
      fetch:
        src: /home/coremark/run1.log
        dest: '{{ cpu_bench_results }}'
  
