- name: Fresh Benchmark Suite Installation
  hosts: "{{ host_group }}"
  become: yes
  
  vars_files:
    - ../vars/local_directories_vars.yml

  remote_user: '{{ remote_host_user }}'
  become_user: '{{ remote_host_user }}'
  
  tasks:
    - name: Run CoreMark Dependencies Installation Script
      script: '../playbook-scripts/install-coremark-deps.py'
      args:
        executable: python3
      register: pkg_inst_output
      failed_when: "'Installing:' in pkg_inst_output.stdout"
      
    - name: Print Script stdout
      debug:
        msg: 'Testing'
      
    - name: Clone CoreMark repository from GitHub
      git:
        repo: https://github.com/eembc/coremark.git
        dest: '/home/{{ remote_host_user }}/coremark'
        clone: yes
        update: yes
- name: Install iperf3
  hosts: "*"
  become: yes
  tasks:
    - name: Run iperf3 APT install
      apt:
        name: "iperf3"
        update_cache: yes
        install_recommends: no
