---
- name: Install CoreMark Benchmark on Ubuntu
  hosts: proxmoxremote
  gather_facts: true
  become_user: root
  
  vars_files:
    - ../vars/local_directories_vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - build-essential
        - git
      register: apt_output

    - name: Clone CoreMark repository
      git:
        repo: https://github.com/eembc/coremark.git
        dest: /tmp/coremark
      become: true

    - name: Compile CoreMark
      command: make -C /tmp/coremark
      become: true

  handlers:
    - name: Display apt output
      debug:
        var: apt_output.stdout_lines

- name: Execute CoreMark Benchmark
  hosts: proxmoxremote
  gather_facts: false
  become_user: root
  
  vars_files:
    - ../vars/local_directories_vars.yml

  tasks:
    - name: Run CoreMark
      command: /tmp/coremark/coremark.exe
      register: coremark_output

    - name: Display CoreMark output
      debug:
        var: coremark_output.stdout_lines
        
    - name: Fetch CoreMark Performance Results
      fetch:
        src: '/tmp/coremark/run1.log'
        dest: '{{ cpu_bench_results }}'

    - name: Fetch CoreMark Validation Results
      fetch:
        src: '/tmp/coremark/run2.log'
        dest: '{{ cpu_bench_results }}'
