---
- name: Install CoreMark Benchmark on Ubuntu
  hosts: proxmoxremote
  gather_facts: true
  become_user: root
  
  vars_files:
    - ../vars/local_directories_vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - build-essential
        - git
      register: apt_output

    - name: Clone CoreMark repository
      git:
        repo: https://github.com/eembc/coremark.git
        dest: /tmp/coremark
      become: true

    - name: Compile CoreMark
      command: make -C /tmp/coremark
      become: true

  handlers:
    - name: Display apt output
      debug:
        var: apt_output.stdout_lines

- name: Execute CoreMark Benchmark
  hosts: proxmoxremote
  gather_facts: true
  become_user: root
  
  vars_files:
    - ../vars/local_directories_vars.yml
    - ../vars/remote_vars.yml
    
  vars:
    file_timestamp: "{{ inventory_hostname }}_{{ ansible_date_time['date'] }}_{{ ansible_date_time['time'] }}"
#    coremark_output_name: "coremark"
    
  vars_prompt:

  - name: coremark_output_name
    prompt: Enter a unique name for the output log file (Do not include file extension)
    private: false
    
  tasks:
    - name: Create new coremark log directory on remote host
      file:
        path: "{{ rem_cpu_bench_results }}"
        state: directory
        mode: u+rw,g+rw,o+rw
  
    - name: Run CoreMark
      command: /tmp/coremark/coremark.exe
      register: coremark_output

    - name: Display CoreMark output
      debug:
        var: coremark_output.stdout_lines
        
    - name: Locate performance log file in remote file system and copy to remote new results directory
      command: "find . -path './run1.log' -exec cp {} {{ rem_cpu_bench_results }}/{{ coremark_output_name }}-performance_{{ file_timestamp }}.log \\;"
      args:
        chdir: "{{ coremark_results_default }}"
       
    - name: Locate performance log file in remote file system and copy to remote new results directory
      command: "find . -path './run2.log' -exec cp {} {{ rem_cpu_bench_results }}/{{ coremark_output_name }}-validation_{{ file_timestamp }}.log \\;"
      args:
       chdir: "{{ coremark_results_default }}"
        
    - name: Fetch CoreMark Performance Results
      fetch:
        src: "{{ rem_cpu_bench_results }}/{{ coremark_output_name }}-performance_{{ file_timestamp }}.log"
        dest: "{{ loc_cpu_bench_results }}"

    - name: Fetch CoreMark Validation Results
      fetch:
        src: "{{ rem_cpu_bench_results }}/{{ coremark_output_name }}-validation_{{ file_timestamp }}.log"
        dest: "{{ loc_cpu_bench_results }}"
