- name: Fresh Benchmark Suite Installation
  hosts: "*"
  become: yes
  tasks:
    - name: Run CoreMark Dependencies Installation Script
      script: '../playbook-scripts/install-coremark-deps.py'
      args:
        executable: python3
    - name: Clone CoreMark repository from GitHub
      git:
        repo: https://github.com/eembc/coremark.git
        dest: /home/coremark
        clone: yes
        update: yes
- name: Install iperf3
  hosts: "*"
  become: yes
  tasks:
    - name: Run iperf3 APT install
      apt:
        name: "iperf3"
        update_cache: yes
        install_recommends: no