---
- name: Install iperf3 Benchmark on Ubuntu
  hosts: all
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install iperf3
      apt:
        name: iperf3
        state: present
      become: true

- name: Execute iperf3 Benchmark
  hosts: controller_machine
  gather_facts: false

  tasks:
    - name: Start iperf3 server
      command: iperf3 -s
      async: 3600
      poll: 0
      register: iperf_server_output

    - name: Display iperf3 server output
      debug:
        var: iperf_server_output.stdout_lines

- name: Execute iperf3 Benchmark
  hosts: remote_machines
  gather_facts: false

  tasks:
    - name: Run iperf3 client
      command: iperf3 -c {{ controller_machine }} -t {{ iperf_duration }}
      register: iperf_client_output

    - name: Display iperf3 client output
      debug:
        var: iperf_client_output.stdout_lines
