---
- name: Install iperf3 Benchmark on Ubuntu Remote Machines
  hosts: proxmoxremote
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install iperf3
      apt:
        name: iperf3
        state: present
      become: true

- name: Start iperf3 Benchmark Server
  hosts: proxmoxlocal
  connection: local
  gather_facts: false
  become: yes

  tasks:
    - name: Start server from local command line
      command: iperf3 -s -F /var/log/iperf3/output.txt --logfile /var/log/iperf3/log.txt
      async: 3600
      poll: 0
#      register: iperf_server_output
      
- name: Execute iperf3 Benchmark Client Connections
  hosts: proxmoxremote
  serial: 1
  gather_facts: false

  tasks:
    - name: Connect iperf3 clients from command line
      command: iperf3 -c 10.50.0.25 -t 10
      register: iperf_client_output

    - name: Displaying iperf3 client-end results
      debug:
        var: iperf_client_output.stdout_lines
        
- name: Stop iperf3 Benchmark Server
  hosts: proxmoxlocal
  connection: local
  gather_facts: true
  become: yes
  
  tasks:
    - name: Run killall command on iperf3 server
      command: killall iperf3


