---
- name: Install iperf3 Benchmark on Ubuntu Remote Machines
  hosts: proxmoxremote
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install iperf3
      apt:
        name: iperf3
        state: present
      become: true

- name: Start iperf3 Benchmark Server
  hosts: proxmoxlocal
  connection: local
  gather_facts: true
  become: yes

  vars_files:
    - ../vars/local_directories_vars.yml
    - ../vars/remote_vars.yml

  vars:
    file_timestamp: "-server-{{ inventory_hostname }}_{{ ansible_date_time['date'] }}_{{ ansible_date_time['time'] }}"
#    server_output_name: "iperf3-server-{{ file_timestamp }}"

  vars_prompt:

  - name: server_output_name
    prompt: "Enter a unique name for the client-side log file (Do not include file extension, \"-server\", hostname, and timestamp are automatically appended)"
    private: false

  tasks:
  
    - name: Create new iperf3 log directory on local host
      file:
        path: "{{ loc_net_bench_results }}"
        state: directory
        mode: u+rw,g+rw,o+rw
  
    - name: Start server from local command line
      command: "iperf3 -s -F /var/log/iperf3/output.txt --logfile {{ loc_net_bench_results }}/{{ server_output_name }}{{ file_timestamp }}.log"
      async: 3600
      poll: 0
      
- name: Execute iperf3 Benchmark Client Connections
  hosts: proxmoxremote
  serial: 1
  gather_facts: false
  become: yes
  
  vars_files:
    - ../vars/local_directories_vars.yml
    - ../vars/remote_vars.yml

  vars:
    file_timestamp: "-client-{{ inventory_hostname }}_{{ ansible_date_time['date'] }}_{{ ansible_date_time['time'] }}"
#    client_output_name: "iperf3-client-{{ file_timestamp }}"

  vars_prompt:

  - name: client_output_name
    prompt: "Enter a unique name for the client-side log file (Do not include file extension, \"-client\", hostname, and timestamp are automatically appended)"
    private: false
  
  tasks:
    - name: Create new iperf3 log directory on remote host
      file:
        path: "{{ rem_net_bench_results }}"
        state: directory
        mode: u+rw,g+rw,o+rw

    - name: Connect iperf3 clients from command line
      command: "iperf3 -c {{ local_ip }} -t 10 --logfile {{ rem_net_bench_results }}/{{ client_output_name }}{{ file_timestamp }}.log"
      register: iperf_client_output

    - name: Displaying iperf3 client-end results
      debug:
        var: iperf_client_output.stdout_lines
      
    - name: Retrieve client log files from remote hosts
      fetch:
        src: "{{ rem_net_bench_results }}/{{ client_output_name }}{{ file_timestamp }}.log"
        dest: "{{ loc_net_bench_results }}"
        
        
- name: Stop iperf3 Benchmark Server
  hosts: proxmoxlocal
  connection: local
  gather_facts: true
  become: yes
  
  tasks:
    - name: Run killall command on iperf3 server
      command: killall iperf3

