---
  # Play to install iperf3 on the controller so the server side of the test can be run locally
- name: Install iperf3 Benchmark on Local Machine
  hosts: 127.0.0.1
  connection: local
  gather_facts: true

  vars_files:
    - ../vars/local_directories_vars.yml

  tasks:
      # Update Ubuntu apt cache
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

      # Use apt module to install iperf3 
    - name: Install iperf3
      apt:
        name: iperf3
        state: present
      become: true
      register: apt_output
      
      # Create new directory on controller to store server-side results and client-side results fetched remotely.
    - name: Create local results directory
      file:
        path: "{{ loc_net_bench_results }}"
        state: directory
        mode: u+rw,g+rw,o+r

  # Use handler to display output of apt update. Do further research on how this works.
  handlers:
    - name: Display apt output
      debug:
        var: apt_output.stdout_lines
