---
- name: Install iperf3 Benchmark on Local Machine
  hosts: 127.0.0.1
  connection: local
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install iperf3
      apt:
        name: iperf3
        state: present
      become: true
      register: apt_output

  handlers:
    - name: Display apt output
      debug:
        var: apt_output.stdout_lines
