---
- name: Install iperf3 Benchmark on Ubuntu Remote Machines
  hosts: proxmoxremote
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install iperf3
      apt:
        name: iperf3
        state: present
      become: true

- name: Execute iperf3 Benchmark Server
  hosts: proxmoxlocal
  connection: local
  gather_facts: false

  tasks:
    - name: Start iperf3 server
      command: iperf3 -s
      async: 3600
      poll: 0
      register: iperf_server_output

#    - name: Display iperf3 server output
#      debug:
#        var: iperf_server_output.stdout_lines
      
- name: Execute iperf3 Benchmark Client
  hosts: proxmoxremote
  serial: 1
  gather_facts: false

  tasks:
    - name: Run iperf3 client connections
      command: iperf3 -c 10.50.0.25 -t 10
      register: iperf_client_output

    - name: Display iperf3 client output
      debug:
        var: iperf_client_output.stdout_lines
        
- name: Kill iperf3 Server
  hosts: proxmoxlocal
  connection: local
  gather_facts: false
  
  tasks:
    - name: Run killall on iperf3
      command: killall iperf3
      register: iperf_server_output

    - name: Display iperf3 server output
      debug:
        var: iperf_server_output.stdout_lines   

