---
- name: Install Phoronix Test Suite and RAMspeed SMP on Ubuntu Desktop
  hosts: proxmoxremote
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install Required APT Packages
      apt:
        name: ['git', 'php', 'php-cli', 'php-dom', 'php-json', 'php-xml', 'php-zip', 'php-gd', 'php-mbstring', 'php-tokenizer', 'php-xmlwriter', 'php-curl', 'php-pear', 'unzip', 'python3-pip', 'python-setuptools', 'virtualenv']
      become: true

    - name: Install pexpect Package Using python3-pip 
      pip:
        name: pexpect

    - name: Clone Phoronix Test Suite from GitHub
      git:
        repo: https://github.com/phoronix-test-suite/phoronix-test-suite.git
        dest: /opt/phoronix-test-suite
      become: true

    - name: Install Phoronix Test Suite
      command: ./install-sh
      args:
        chdir: /opt/phoronix-test-suite
      become: true

    - name: Run Phoronix Test Suite Self-Test
      command: ./phoronix-test-suite self-test
      args:
        chdir: /opt/phoronix-test-suite
      become: true

    - name: Install RAMspeed SMP benchmark
      command: ./phoronix-test-suite install ram-speed
      args:
        chdir: /opt/phoronix-test-suite
      become: true
      
    - name: Install Flexible I/O Storage Benchmark Suite
      command: ./phoronix-test-suite install fio
      args:
        chdir: /opt/phoronix-test-suite
      become: true
