- name: Run Benchmarks
  hosts: "*"
  become: yes
  tasks:
    - name: Run Python Sript to Run CoreMark
      script: '../playbook-scripts/run-coremark.py'
      args:
        executable: python3
