---
- name: Execute Flexible I/O Storage Benchmark
  hosts: ans-remote0
  become: false
  
  vars_files:
    - ../vars/local_directories_vars.yml
    - ../vars/remote_vars.yml

  vars_prompt:
  
  - name: test_type
    prompt: |
      Select the type of test to run
      
      1: Random Read
      2: Random Write
      3: Sequential Read
      4: Sequential Write
      5: Test All Options
      ** Multiple items can be selected, delimit by a comma. **
      Type
    private: false
    
  - name: test_engine
    prompt: |
        
        Choose the test engine
        
        1: IO_uring
        2: POSIX AIO
        3: Sync
        4: Linux AIO
        5: Test All Options
        ** Multiple items can be selected, delimit by a comma. **
        Engine
    private: false

  - name: test_buffer
    prompt: |
        
        Buffer I/O?
    
        1: Yes
        2: No
        3: Test All Options
        ** Multiple items can be selected, delimit by a comma. **
        Buffered
    private: false
  
  - name: test_direct
    prompt: |
        
        Direct I/O?
        
        1: No
        2: Yes
        3: Test All Options
        ** Multiple items can be selected, delimit by a comma. **
        Direct
    private: false
  
  - name: test_block
    prompt: |
        
        Choose block size
        
        1:  4KB
        2:  8KB
        3:  16KB
        4:  32KB
        5:  64KB
        6:  128KB
        7:  256KB
        8:  512KB
        9:  1MB
        10: 2MB
        11: 4MB
        12: 8MB
        13: Test All Options
        ** Multiple items can be selected, delimit by a comma. **
        Block Size
    private: false
    
  - name: test_filename
    prompt: Enter a name for the result file (do not include file extension or timestamp)
    private: false
    
  - name: test_name
    prompt: Enter a unique name to describe this test run / configuration
    private: false
    
  - name: test_desc
    prompt: |
      If desired, enter a new description below to better describe this result set / system configuration under test.
      Press ENTER to proceed without changes.
      
      New Description
    private: false
  
  vars:
    file_timestamp: "{{ inventory_hostname }}_{{ ansible_date_time['date'] }}_{{ ansible_date_time['time'] }}"
  
  tasks:
  - name: Handle FIO Errors
    block:
      - name: Execute FIO from command line
        expect:
          command: phoronix-test-suite benchmark fio
          responses:
            "Type:": "{{ test_type }}"
            "Engine:": "1"
            "Buffered:": "1"
            "Direct:": "1"
            "Block Size:": "1"
            "Disk Target:": "1"
            "Would you like to save these test results \\(Y\\/n\\):": "Y"
            "Enter a name for the result file:": "{{ test_filename }}"
            "Enter a unique name to describe this test run / configuration:": "{{ test_name }}"
            "New Description:": "{{ test_desc }}"
            "Do you want to view the text results of the testing \\(Y\\/n\\):": "n"
            "Would you like to upload the results to OpenBenchmarking.org \\(y\\/n\\):": "n"
            
          echo: false
          timeout: null
        register: fio_out
        become: true

    always:
      - name: Display Results
        debug:
          var: fio_out
        become: true
          
  - name: Locate log files in remote file system and copy to results directory
    command: "find . -path './*/{{ test_filename }}.log' -exec cp {} {{ rem_stor_bench_results }}/{{ test_filename }}_{{ file_timestamp }}.log \\;"
    args:
      chdir: "{{ phoronix_results }}"
  
  - name: Retrieve FIO Results Files
    fetch:
      src: '{{ rem_stor_bench_results }}/{{ test_filename }}_{{ file_timestamp }}.log'
      dest: '{{ loc_stor_bench_results }}'

      
